USE [Saiko-intranet]
GO

INSERT INTO [dbo].[Banks]
    ([socialReason]
    ,[shortName]
    ,[status]
    ,[createdBy]
    ,[createdDate]
    ,[lastUpdatedBy]
    ,[lastUpdatedDate]
    ,[clave])
VALUES
    ('Banco Nacional de México, S.A., Institución de Banca Múltiple, Grupo Financiero Banamex',
        'BANAMEX',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        002
        ),
    ('Banco Nacional de Comercio Exterior, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo',
        'BANCOMEXT',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        006
        ),
    ('Banco Nacional de Comercio Exterior, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo',
        'BANCOMEXT',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        009
        ),
    ('BBVA Bancomer, S.A., Institución de Banca Múltiple, Grupo Financiero BBVA Bancomer',
        'BBVA BANCOMER',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        012
        ),
    ('Banco Santander (México), S.A., Institución de Banca Múltiple, Grupo Financiero Santander',
        'SANTANDER',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        014
        ),
    ('Banco Nacional del Ejército, Fuerza Aérea y Armada, Sociedad Nacional de Crédito,
Institución de Banca de Desarrollo',
        'BANJERCITO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        019
        ),
    ('HSBC México, S.A., institución De Banca Múltiple, Grupo Financiero HSBC',
        'HSBC',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        021
        ),
    ('Banco del Bajío, S.A., Institución de Banca Múltiple',
        'BAJIO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        030
        ),
    ('IXE Banco, S.A., Institución de Banca Múltiple, IXE Grupo Financiero',
        'IXE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        032
        ),
    ('Banco Inbursa, S.A., Institución de Banca Múltiple, Grupo Financiero Inbursa',
        'INBURSA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        036
        ),
    ('Banco Interacciones, S.A., Institución de Banca Múltiple',
        'INTERACCIONES',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        037
        ),
    ('Banca Mifel, S.A., Institución de Banca Múltiple, Grupo Financiero Mifel',
        'MIFEL',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        042
        ),
    ('Scotiabank Inverlat, S.A',
        'SCOTIABANK',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        044
        ),
    ('Banco Regional de Monterrey, S.A., Institución de Banca Múltiple, Banregio Grupo
Financiero',
        'BANREGIO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        058
        ),
    ('Banco Invex, S.A., Institución de Banca Múltiple, Invex Grupo Financiero',
        'INVEX',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        059
        ),
    ('Bansi, S.A., Institución de Banca Múltiple',
        'BANSI',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        060
        ),
    ('Banca Afirme, S.A., Institución de Banca Múltiple',
        'AFIRME',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        062
        ),
    ('Banco Mercantil del Norte, S.A., Institución de Banca Múltiple, Grupo Financiero Banorte',
        'BANORTE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        072
        ),
    ('The Royal Bank of Scotland México, S.A., Institución de Banca Múltiple',
        'THE ROYAL BANK',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        102
        ),
    ('American Express Bank (México), S.A., Institución de Banca Múltiple',
        'AMERICAN EXPRESS',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        103
        ),
    ('Bank of America México, S.A., Institución de Banca Múltiple, Grupo Financiero Bank of America',
        'BAMSA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        106
        ),
    ('Bank of Tokyo-Mitsubishi UFJ (México), S.A.',
        'TOKYO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        108
        ),
    ('Banco J.P. Morgan, S.A., Institución de Banca Múltiple, J.P. Morgan Grupo Financiero',
        'JP MORGAN',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        110
        ),
    ('Banco Monex, S.A., Institución de Banca Múltiple',
        'BMONEX',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        112
        ),
    ('Banco Ve Por Mas, S.A. Institución de Banca Múltiple',
        'VE POR MAS',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        113
        ),
    ('ING Bank (México), S.A., Institución de Banca Múltiple, ING Grupo Financiero',
        'ING',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        116
        ),
    ('Deutsche Bank México, S.A., Institución de Banca Múltiple',
        'DEUTSCHE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        124
        ),
    ('Banco Credit Suisse (México), S.A. Institución de Banca Múltiple, Grupo Financiero Credit Suisse (México)',
        'CREDIT SUISSE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        126
        ),
    ('Banco Azteca, S.A. Institución de Banca Múltiple.',
        'AZTECA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        127
        ),
    ('Banco Autofin México, S.A. Institución de Banca Múltiple',
        'AUTOFIN',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        128
        ),
    ('Barclays Bank México, S.A., Institución de Banca Múltiple, Grupo Financiero Barclays México',
        'BARCLAYS',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        129
        ),
    ('Banco Compartamos, S.A., Institución de Banca Múltiple',
        'COMPARTAMOS',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        130
        ),
    ('Banco Ahorro Famsa, S.A., Institución de Banca Múltiple',
        'BANCO FAMSA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        131
        ),
    ('Banco Multiva, S.A., Institución de Banca Múltiple, Multivalores Grupo Financiero',
        'BMULTIVA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        132
        ),
    ('Banco Actinver, S.A. Institución de Banca Múltiple, Grupo Financiero Actinver',
        'ACTINVER',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        133
        ),
    ('Banco Wal-Mart de México Adelante, S.A., Institución de Banca Múltiple',
        'WAL-MART',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        134
        ),
    ('Nacional Financiera, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo',
        'NAFIN',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        135
        ),
    ('Inter Banco, S.A. Institución de Banca Múltiple',
        'INTERBANCO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        136
        ),
    ('BanCoppel, S.A., Institución de Banca Múltiple',
        'BANCOPPEL',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        137
        ),
    ('ABC Capital, S.A., Institución de Banca Múltiple',
        'ABC CAPITAL',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        138
        ),
    ('UBS Bank México, S.A., Institución de Banca Múltiple, UBS Grupo Financiero',
        'UBS BANK',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        139
        ),
    ('Consubanco, S.A. Institución de Banca Múltiple',
        'CONSUBANCO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        140
        ),
    ('Volkswagen Bank, S.A., Institución de Banca Múltiple',
        'VOLKSWAGEN',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        141
        ),
    ('CIBanco, S.A.',
        'CIBANCO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        143
        ),
    ('Banco Base, S.A., Institución de Banca Múltiple',
        'BBASE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        145
        ),
    ('Banco del Ahorro Nacional y Servicios Financieros, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo',
        'BANSEFI',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        166
        ),
    ('Sociedad Hipotecaria Federal, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo',
        'HIPOTECARIA FEDERAL',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        168
        ),
    ('Sociedad Hipotecaria Federal, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo',
        'HIPOTECARIA FEDERAL',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        168
        ),
    ('Monex Casa de Bolsa, S.A. de C.V. Monex Grupo Financiero',
        'MONEXCB',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        600
        ),
    ('GBM Grupo Bursátil Mexicano, S.A. de C.V. Casa de Bolsa',
        'GBM',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        601
        ),
    ('Masari Casa de Bolsa, S.A.',
        'MASARI',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        602
        ),
    ('Value, S.A. de C.V. Casa de Bolsa',
        'VALUE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        605
        ),
    ('Estructuradores del Mercado de Valores Casa de Bolsa, S.A. de C.V.',
        'ESTRUCTURADORES',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        606
        ),
    ('Casa de Cambio Tiber, S.A. de C.V.',
        'TIBER',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        607
        ),
    ('Vector Casa de Bolsa, S.A. de C.V.',
        'VECTOR',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        608
        ),
    ('B y B, Casa de Cambio, S.A. de C.V.',
        'B&B',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        610
        ),
    ('Acciones y Valores Banamex, S.A. de C.V., Casa de Bolsa',
        'ACCIVAL',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        614
        ),
    ('Merrill Lynch México, S.A. de C.V. Casa de Bolsa',
        'MERRILL LYNCH',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        615
        ),
    ('Casa de Bolsa Finamex, S.A. de C.V.',
        'FINAMEX',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        616
        ),
    ('Valores Mexicanos Casa de Bolsa, S.A. de C.V.',
        'VALMEX',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        617
        ),
    ('Unica Casa de Cambio, S.A. de C.V.',
        'UNICA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        618
        ),
    ('MAPFRE Tepeyac, S.A.',
        'MAPFRE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        619
        ),
    ('Profuturo G.N.P., S.A. de C.V., Afore',
        'PROFUTURO',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        620
        ),
    ('Actinver Casa de Bolsa, S.A. de C.V.',
        'CB ACTINVER',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        621
        ),
    ('OPERADORA ACTINVER, S.A. DE C.V.',
        'OACTIN',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        622
        ),
    ('Skandia Vida, S.A. de C.V.',
        'SKANDIA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        623
        ),
    ('Deutsche Securities, S.A. de C.V. CASA DE BOLSA',
        'CBDEUTSCHE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        626
        ),
    ('Zurich Compañía de Seguros, S.A.',
        'ZURICH',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        627
        ),
    ('Zurich Vida, Compañía de Seguros, S.A.',
        'ZURICHVI',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        628
        ),
    ('Hipotecaria Su Casita, S.A. de C.V. SOFOM ENR',
        'SU CASITA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        629
        ),
    ('Hipotecaria Su Casita, S.A. de C.V. SOFOM ENR',
        'SU CASITA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        629
        ),
    ('Intercam Casa de Bolsa, S.A. de C.V.',
        'CB INTERCAM',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        630
        ),
    ('CI Casa de Bolsa, S.A. de C.V.',
        'CI BOLSA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        631
        ),
    ('Bulltick Casa de Bolsa, S.A., de C.V.',
        'BULLTICK CB',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        632
        ),
    ('Sterling Casa de Cambio, S.A. de C.V.',
        'STERLING',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        633
        ),
    ('Fincomún, Servicios Financieros Comunitarios, S.A. de C.V.',
        'FINCOMUN',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        634
        ),
    ('HDI Seguros, S.A. de C.V.',
        'HDI SEGUROS',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        636
        ),
    ('Order Express Casa de Cambio, S.A. de C.V',
        'ORDER',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        637
        ),
    ('Akala, S.A. de C.V., Sociedad Financiera Popular',
        'AKALA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        638
        ),
    ('J.P. Morgan Casa de Bolsa, S.A. de C.V. J.P. Morgan Grupo Financiero',
        'CB JPMORGAN',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        640
        ),
    ('Operadora de Recursos Reforma, S.A. de C.V., S.F.P.',
        'REFORMA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        642
        ),
    ('Sistema de Transferencias y Pagos STP, S.A. de C.V.SOFOM ENR',
        'STP',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        646
        ),
    ('Telecomunicaciones de México',
        'TELECOMM',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        647
        ),
    ('Evercore Casa de Bolsa, S.A. de C.V.',
        'EVERCORE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        648
        ),
    ('Skandia Operadora de Fondos, S.A. de C.V.',
        'SKANDIA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        649
        ),
    ('Seguros Monterrey New York Life, S.A de C.V',
        'SEGMTY',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        651
        ),
    ('Solución Asea, S.A. de C.V., Sociedad Financiera Popular',
        'ASEA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        652
        ),
    ('Kuspit Casa de Bolsa, S.A. de C.V.',
        'KUSPIT',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        653
        ),
    ('J.P. SOFIEXPRESS, S.A. de C.V., S.F.P.',
        'SOFIEXPRESS',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        655
        ),
    ('UNAGRA, S.A. de C.V., S.F.P.',
        'UNAGRA',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        656
        ),
    ('OPCIONES EMPRESARIALES DEL NORESTE, S.A. DE C.V., S.F.P.',
        'OPCIONES EMPRESARIALES DEL NOROESTE',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        659
        ),
    ('Cls Bank International',
        'CLS',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        901
        ),
    ('SD. Indeval, S.A. de C.V.',
        'INDEVAL',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        902
        ),
    ('Libertad Servicios Financieros, S.A. De C.V.',
        'LIBERTAD',
        1,
        'Adrian Alardin Iracheta',
        GETDATE(),
        'Adrian Alardin Iracheta',
        GETDATE(),
        670
        )

GO


