-- *******************************************************************************************************************************
--	STORED PROCEDURE OVERVIEW INFORMATION
-- *******************************************************************************************************************************
-- Author:      Jose Luis Perez Olguin
-- Create date: 16-11-2021
-- Description: Add the XML and PDF file resulting of create the invoice for the SAT
-- STORED PROCEDURE NAME:	sp_AddFilesInvoice
-- *******************************************************************************************************************************
-- PARAMETERS:
-- @uuid: UUID of the invoice document generated by the SAT
-- @xml: URL where the XML file can be downloaded (it's on azure blob)
-- @pdf: URL where the PDF file can be downloaded (it's on azure blob)
-- @idProviderInvoice: ID that the provider use to reference the created SAT's invoice
-- @updatedBy: Name of the executive who performed the action of create the invoice
-- @idPreinvoice: Id of the preinvoice
-- *******************************************************************************************************************************
--	REVISION HISTORY/LOG
-- *******************************************************************************************************************************
--	Date			Programmer					Revision	    Revision Notes
-- =================================================================================================
--	16-11-2021		Jose Luis Perez Olguin   			1.0.0.0			Initial Revision
-- *******************************************************************************************************************************

CREATE PROCEDURE sp_AddFilesInvoice(
    @uuid NVARCHAR(256), 
    @xml NVARCHAR(256),
    @pdf NVARCHAR(256),
    @idProviderInvoice NVARCHAR(256),
    @updatedBy NVARCHAR(30),
    @idPreinvoice INT,
)

AS BEGIN

    exec sp_AddFileBlobAzure @updatedBy,'PDF Prefactura',@idPreinvoice,'pdf', @pdf;
    exec sp_AddFileBlobAzure @updatedBy,'XML Prefactura',@idPreinvoice,'xml', @xml;

    UPDATE Documents SET
        uuid = @uuid,
        hasAttachedFiles = 1,
        xml = @xml,
        pdf = @pdf,
        invoiceMizarNumber = @idProviderInvoice,
        lastUpdatedBy = @updatedBy,
        lastUpdatedDate = GETDATE() 
    WHERE idDocument = @idPreinvoice;

END